export enum PaymentStatus {
    PENDING = 'PENDING',
    PAID = 'PAID',
    PAYMENT_FAILED = 'PAYMENT_FAILED',
    REFUND_INITIATED = 'REFUND_INITIATED',
    REFUNDED = 'REFUNDED',
    COD_PENDING = 'COD_PENDING',
    COD_COLLECTED = 'COD_COLLECTED',
    COD_FAILED = 'COD_FAILED'
}