export enum PaymentMethod {
    CREDIT_CARD = 'CREDIT_CARD',
    DEBIT_CARD = 'DEBIT_CARD',
    PAYPAL = 'PAYPAL',
    COD = 'COD',
    BANK_TRANSFER = 'BANK_TRANSFER',
    MOBILE_PAYMENT = 'MOBILE_PAYMENT'
}
